# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dropbox}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Morgan"]
  s.date = %q{2010-05-24}
  s.description = %q{An easy-to-use client library for the official Dropbox API.}
  s.email = %q{dropbox@timothymorgan.info}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dropbox.gemspec",
     "lib/dropbox.rb",
     "lib/dropbox/api.rb",
     "lib/dropbox/entry.rb",
     "lib/dropbox/event.rb",
     "lib/dropbox/memoization.rb",
     "lib/dropbox/revision.rb",
     "lib/dropbox/session.rb",
     "lib/extensions/array.rb",
     "lib/extensions/hash.rb",
     "lib/extensions/module.rb",
     "lib/extensions/object.rb",
     "lib/extensions/string.rb",
     "lib/extensions/to_bool.rb",
     "spec/dropbox/api_spec.rb",
     "spec/dropbox/entry_spec.rb",
     "spec/dropbox/event_spec.rb",
     "spec/dropbox/revision_spec.rb",
     "spec/dropbox/session_spec.rb",
     "spec/dropbox_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/RISCfuture/dropbox}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby client library for the official Dropbox API}
  s.test_files = [
    "spec/dropbox/api_spec.rb",
     "spec/dropbox/entry_spec.rb",
     "spec/dropbox/event_spec.rb",
     "spec/dropbox/revision_spec.rb",
     "spec/dropbox/session_spec.rb",
     "spec/dropbox_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<multipart-post>, [">= 1.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
      s.add_dependency(%q<multipart-post>, [">= 1.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<oauth>, [">= 0.3.6"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
    s.add_dependency(%q<multipart-post>, [">= 1.0"])
  end
end

